canonical/craft-grammar

craft_grammar/__init__.py
docs/changelog.rst

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----

Release 1.1.0

---

craft_grammar/models.py
tests/unit/test_models.py

Grammar is expressed as a list of one-entry dictionaries. Previous
code validated it as a dictionary, so fix the validators to use the
correct data structures.
This is a follow-up to PR #4 (CRAFT-856).
**Note to reviewers:** please make sure that the yaml definition in
`test_validate_grammar_recursive` is syntactically correct.
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>
-----

models: fix grammar validation

---

pyrightconfig.json

style: make pyright less concerned about grammar methods

---

.github/workflows/tests.yaml
.readthedocs.yml
docs/requirements.txt
pyproject.toml
setup.cfg

build!: drop support for Python 3.8

---

craft_grammar/create.py
craft_grammar/models.py
pyproject.toml
tests/unit/test_create.py
tests/unit/test_models.py

Most of the breaking changes are in the reported messages for grammar validation errors.
Fixes #32
-----

chore!: update to Pydantic 2

---

craft_grammar/models.py
tests/unit/test_models.py

This makes grammar models work with annotated types.
-----

fix(models): make grammar models work with Annotated

---

.bumpversion.cfg
craft_grammar/__init__.py
docs/changelog.rst

Also bumps the internal version
-----

docs: add 2.0.0 changelog

---

.pre-commit-config.yaml
pyproject.toml
tests/conftest.py

build(deps): update to ruff 0.6.1

---

docs/changelog.rst

docs(changelog): add 2.0.1

---

pyproject.toml

fix(docs): get the correct readme for pypi

---

.github/workflows/security-scan.yaml

ci: add security scanning workflow

---

craft_grammar/_processor.py
craft_grammar/create.py
tests/unit/test_processor.py

fix: handle multi-entry dictionary after grammar statement

---

docs/changelog.rst

docs(changelog): add 2.0.2

---

.github/workflows/release-publish.yaml

ci: use Trusted Publishing for PyPI releases

---

docs/changelog.rst

docs(changelog): add 2.0.3

---

.github/.jira_sync_config.yaml

Update Jira sync labels to match our new labels
-----
CRAFT-4215

ci: update Jira sync config

---

.github/workflows/tests.yaml

ci: swap Ubuntu focal for noble

---

pyproject.toml
uv.lock

---
This PR replaces renovate PR #97, which is inexplicably broken.

build: bump dependency versions

---

craft_grammar/__init__.py
craft_grammar/_base_processor.py
craft_grammar/_for.py
craft_grammar/_processor.py
craft_grammar/errors.py
tests/integration/data/valid/for.for-platform1.yaml
tests/integration/data/valid/for.for-platform2.yaml
tests/integration/data/valid/for.for-platform3.yaml
tests/integration/data/valid/for.validated.yaml
tests/integration/data/valid/for.yaml
tests/integration/test_processor.py
tests/unit/test_base_processor.py

feat: add "any" as an always-on value for "for" grammar

---

craft_grammar/_base_processor.py
craft_grammar/_processor.py
tests/integration/data/invalid/for-and-on.yaml
tests/unit/test_processor.py

feat: allow the app to select the grammar variant

---

docs/changelog.rst

docs: 2.3.0 changelog
